exp: TokenClassification

mode: 
    - interact
    - evaluate

models: 
      hf_token_classification_model:
          - QCRI/bert-base-multilingual-cased-pos-english

datafpath: data/pos.tsv

predfpath: predictions/pos.tsv
