name: nlp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=22.2.2
  - pip:
    - accelerate==0.33.0
    - bitsandbytes==0.42.0
    - numpy==1.26.4
    - pandas==2.2.2
    - scipy==1.14.0
    - sentencepiece==0.2.0
    - tokenizers==0.19.1
    - torch==2.4.0
    - transformers==4.43.3
    - typing-extensions==4.12.2
